# Generated by Django 2.2.4 on 2021-04-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
