# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c40c62928b21d9471397ce4eff9a25f4a1606d8447295dce2cb7cd7c3799fd92a028966bfa79ff815952990d67b7c97a182b44858c51c85be0759eca28b1525f

test:
  secret_key_base: f3d2c967948ea4ca069f366e2c04de111f144283a8b82ed5a23293d107b9467bccb130f4dc00be5d50fcad9ab6d3e1977330817e89e4687d67455fc30fb6b32e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
