# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d108e67b98b6f29526a12ea7043ba6248f85f61bc0faec9004ec397f27fc8652bdf2ec8e94e702f7f666d07d069afda3f857f2847a45a1f7f6d0622749e320d

test:
  secret_key_base: d22a3bd4e11d8f94e9aa58f2aa1ef252c6eb74a7bc6cbc35bb20f19fae1f5ec11cc7ee502b23addcd322e5b8b1460bce60e5a4b5b1b6c9a67078020a71ca7abd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
